version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/build/

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: script/deploy.sh
      timeout: 60
      runas: ec2-user
  VaildateService:
    - location: script/healthCheck.sh
      timeout: 60
      runas: ec2-user