version: 0.2

phases:
  install:
    runtime-version:
      java: corretto8
    commands:
      - java -version
      - mvn package
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd

cache:
  paths:
    - '/root/.gradle/caches/**/*'
